# Generated by Django 4.1.3 on 2022-11-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.CharField(default='description to the title1', max_length=500),
        ),
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.CharField(default='title1', max_length=100),
        ),
    ]
