# Generated by Django 4.1.3 on 2022-11-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_feature_description_feature_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title1', max_length=100)),
                ('description', models.CharField(default='description to the title1', max_length=500)),
            ],
        ),
    ]
